---
# tasks file for ansible-role-smtpdebuggingserver

- name: create systemd unit file
  template:
    src: smtp_debugging_server.service.j2
    dest: /etc/systemd/system/smtp_debugging_server.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart smtp_debugging_server service
